steps:    
    - id: "Install GO Lang"
      name: "gcr.io/cloud-builders/go"
      args: ['install', 'calc']
      env: ['GOPATH=.']

    - id: "Run test GO Lang"
      name: "gcr.io/cloud-builders/go"
      args: ['test', 'calc']
      env: ['GOPATH=.']
      
    - id: "Build App Calc"
      name: 'gcr.io/cloud-builders/docker'
      args: ['build', '--tag=gcr.io/$PROJECT_ID/calc', '.']

images: ['gcr.io/$PROJECT_ID/calc']