version: '3'

services: 

    work:
        image: golang:1.14-alpine
        volumes:
          - ./src:/go/src/app
        working_dir: /go/src/app
        container_name: go-test  

    app:
        build:
          context: .
          dockerfile: .docker/app/Dockerfile        
        container_name: app

    
